package latte

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/licenselatte/latte-go/internal/core/domain"
	"github.com/licenselatte/latte-go/internal/core/ports"
	"github.com/licenselatte/latte-go/internal/infra/validate"
	"github.com/licenselatte/latte-go/internal/infra/verify"
)

// fixture mirrors the shared, language-agnostic test vector format defined
// in ../SPEC.md section 2.3 and generated by latte-testvectors/generator.
// This file is latte-go's half of the "retrofit if needed" instruction in
// the porting task: every SDK's test suite runs the identical fixtures and
// must agree on accept/reject/error-stage/error-reason for every one.
type fixture struct {
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Now         time.Time `json:"now"`

	MasterPublicKeyHex string `json:"master_public_key_hex"`
	MachineID          string `json:"machine_id"`

	Token string `json:"token"`
	Chain struct {
		Submaster string `json:"submaster"`
		Project   string `json:"project"`
		Daily     string `json:"daily"`
	} `json:"chain"`

	Expect        string `json:"expect"`
	ExpectStage   string `json:"expect_stage"`
	ExpectReason  string `json:"expect_reason"`
	ExpectInGrace bool   `json:"expect_in_grace_period"`

	ExpectHasEntitlements bool           `json:"expect_has_entitlements"`
	ExpectEntitlements    map[string]any `json:"expect_entitlements"`
}

func loadFixtures(t *testing.T) []fixture {
	t.Helper()
	matches, err := filepath.Glob("testdata/vectors/*.json")
	if err != nil {
		t.Fatalf("glob testdata: %v", err)
	}
	var out []fixture
	for _, path := range matches {
		if filepath.Base(path) == "manifest.json" {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		var f fixture
		if err := json.Unmarshal(data, &f); err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		out = append(out, f)
	}
	if len(out) == 0 {
		t.Fatal("no fixtures found in testdata/ — did you forget to populate the submodule?")
	}
	return out
}

// reasonFor classifies a validate-stage error into the small reason
// taxonomy documented in latte-testvectors/README.md, so every SDK's test
// runner can assert the same string regardless of native error type.
func reasonFor(err error) string {
	switch {
	case errors.Is(err, ports.ErrLicenseInactiveOrExpired):
		return "hard_expired"
	case errors.Is(err, ports.ErrGracePeriodExpired):
		return "grace_expired"
	case errors.Is(err, ports.ErrLicenseTooOld):
		return "license_too_old"
	case err != nil && err.Error() == "invalid license: machine_id does not match":
		return "machine_id_mismatch"
	default:
		return "other"
	}
}

func TestFixtures(t *testing.T) {
	for _, f := range loadFixtures(t) {
		f := f
		t.Run(f.Name, func(t *testing.T) {
			masterPub, err := hex.DecodeString(f.MasterPublicKeyHex)
			if err != nil {
				t.Fatalf("bad master_public_key_hex: %v", err)
			}
			chain := &domain.CertChain{
				Submaster: f.Chain.Submaster,
				Project:   f.Chain.Project,
				Daily:     f.Chain.Daily,
			}

			lic, verr := verify.VerifyActivationAt(masterPub, f.Token, chain, f.Now)
			if verr != nil {
				if f.Expect != "reject" || f.ExpectStage != "verify" {
					t.Fatalf("unexpected verify-stage failure: %v (want expect=%s stage=%s)", verr, f.Expect, f.ExpectStage)
				}
				return
			}
			if f.Expect == "reject" && f.ExpectStage == "verify" {
				t.Fatalf("expected verify-stage rejection, but chain verification succeeded")
			}

			vaerr := validate.ValidateAt(lic, f.MachineID, f.Now)
			if vaerr != nil {
				if f.Expect != "reject" || f.ExpectStage != "validate" {
					t.Fatalf("unexpected validate-stage failure: %v (want expect=%s stage=%s)", vaerr, f.Expect, f.ExpectStage)
				}
				if got := reasonFor(vaerr); got != f.ExpectReason {
					t.Fatalf("validate-stage reason mismatch: got %q, want %q (err: %v)", got, f.ExpectReason, vaerr)
				}
				return
			}

			if f.Expect != "accept" {
				t.Fatalf("expected rejection (stage=%s reason=%s) but both verify and validate succeeded", f.ExpectStage, f.ExpectReason)
			}

			sinceActivation := f.Now.Sub(lic.IssuedAt)
			inGrace := sinceActivation > maxRenewalTime && sinceActivation < lic.GracePeriod
			if inGrace != f.ExpectInGrace {
				t.Fatalf("InGracePeriod mismatch: got %v, want %v", inGrace, f.ExpectInGrace)
			}

			// Through domainToPublic rather than decodeEntitlements directly,
			// so the assertion covers the wiring an application actually gets
			// back from Activate and Check, not just the decoder.
			assertEntitlements(t, domainToPublic(lic), f)
		})
	}
}

// assertEntitlements checks the shared entitlement contract from
// latte-testvectors/README.md against one fixture.
//
// It asserts the *accessors*, not just the map, because the map is the easy
// half: the rules that actually split implementations are the ones about
// input an SDK does not like — a malformed value that must be dropped rather
// than raised on, and the two coercions (a falsy 0, a boolean read as 1) that
// must miss rather than convert.
func assertEntitlements(t *testing.T, lic *License, f fixture) {
	t.Helper()

	if got := lic.HasEntitlements(); got != f.ExpectHasEntitlements {
		t.Errorf("HasEntitlements() = %v, want %v", got, f.ExpectHasEntitlements)
	}
	if got, want := len(lic.Entitlements), len(f.ExpectEntitlements); got != want {
		t.Fatalf("Entitlements = %v, want %v", lic.Entitlements, f.ExpectEntitlements)
	}

	for key, want := range f.ExpectEntitlements {
		switch want := want.(type) {
		case bool:
			if got := lic.Can(key); got != want {
				t.Errorf("Can(%q) = %v, want %v", key, got, want)
			}
			// No coercion: a boolean is not 1 or 0.
			if got, ok := lic.Limit(key); ok {
				t.Errorf("Limit(%q) = (%d, true) on a boolean entitlement, want a miss", key, got)
			}
		case float64: // every JSON number decodes to float64 here
			got, ok := lic.Limit(key)
			if !ok {
				t.Errorf("Limit(%q) missed, want %v", key, int64(want))
				continue
			}
			if got != int64(want) {
				t.Errorf("Limit(%q) = %d, want %d", key, got, int64(want))
			}
			if want == float64(Unlimited) && got != Unlimited {
				t.Errorf("Limit(%q) = %d, want the Unlimited sentinel %d", key, got, Unlimited)
			}
			// No coercion: an integer is not truthy, not even a non-zero one.
			if lic.Can(key) {
				t.Errorf("Can(%q) = true on an integer entitlement, want false", key)
			}
		default:
			t.Fatalf("fixture %s: expect_entitlements[%q] is %T, but the format admits only bool and integer", f.Name, key, want)
		}
	}

	// Absence denies, whether or not the claim was there at all.
	if lic.Can("no_such_entitlement_key") {
		t.Error("Can() on an unset key returned true; absence must deny")
	}
	if _, ok := lic.Limit("no_such_entitlement_key"); ok {
		t.Error("Limit() on an unset key reported present; absence must deny")
	}
}
