package latte

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/licenselatte/latte-go/internal/core/domain"
	"github.com/licenselatte/latte-go/internal/core/ports"
	"github.com/licenselatte/latte-go/internal/infra/validate"
	"github.com/licenselatte/latte-go/internal/infra/verify"
)

// fixture mirrors the shared, language-agnostic test vector format defined
// in ../SPEC.md section 2.1 and generated by latte-testvectors/generator.
// This file is latte-go's half of the "retrofit if needed" instruction in
// the porting task: every SDK's test suite runs the identical fixtures and
// must agree on accept/reject/error-stage/error-reason for every one.
type fixture struct {
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Description string    `json:"description"`
	Now         time.Time `json:"now"`

	MasterPublicKeyHex string `json:"master_public_key_hex"`
	MachineID          string `json:"machine_id"`

	Token string `json:"token"`
	Chain struct {
		Submaster string `json:"submaster"`
		Project   string `json:"project"`
		Daily     string `json:"daily"`
	} `json:"chain"`

	Expect        string `json:"expect"`
	ExpectStage   string `json:"expect_stage"`
	ExpectReason  string `json:"expect_reason"`
	ExpectInGrace bool   `json:"expect_in_grace_period"`
}

func loadFixtures(t *testing.T) []fixture {
	t.Helper()
	matches, err := filepath.Glob("testdata/*.json")
	if err != nil {
		t.Fatalf("glob testdata: %v", err)
	}
	var out []fixture
	for _, path := range matches {
		if filepath.Base(path) == "manifest.json" {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		var f fixture
		if err := json.Unmarshal(data, &f); err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}
		out = append(out, f)
	}
	if len(out) == 0 {
		t.Fatal("no fixtures found in testdata/ — did you forget to populate the submodule?")
	}
	return out
}

// reasonFor classifies a validate-stage error into the small reason
// taxonomy documented in latte-testvectors/README.md, so every SDK's test
// runner can assert the same string regardless of native error type.
func reasonFor(err error) string {
	switch {
	case errors.Is(err, ports.ErrLicenseInactiveOrExpired):
		return "hard_expired"
	case errors.Is(err, ports.ErrGracePeriodExpired):
		return "grace_expired"
	case errors.Is(err, ports.ErrLicenseTooOld):
		return "license_too_old"
	case err != nil && err.Error() == "invalid license: machine_id does not match":
		return "machine_id_mismatch"
	default:
		return "other"
	}
}

func TestFixtures(t *testing.T) {
	for _, f := range loadFixtures(t) {
		f := f
		t.Run(f.Name, func(t *testing.T) {
			masterPub, err := hex.DecodeString(f.MasterPublicKeyHex)
			if err != nil {
				t.Fatalf("bad master_public_key_hex: %v", err)
			}
			chain := &domain.CertChain{
				Submaster: f.Chain.Submaster,
				Project:   f.Chain.Project,
				Daily:     f.Chain.Daily,
			}

			lic, verr := verify.VerifyActivationAt(masterPub, f.Token, chain, f.Now)
			if verr != nil {
				if f.Expect != "reject" || f.ExpectStage != "verify" {
					t.Fatalf("unexpected verify-stage failure: %v (want expect=%s stage=%s)", verr, f.Expect, f.ExpectStage)
				}
				return
			}
			if f.Expect == "reject" && f.ExpectStage == "verify" {
				t.Fatalf("expected verify-stage rejection, but chain verification succeeded")
			}

			vaerr := validate.ValidateAt(lic, f.MachineID, f.Now)
			if vaerr != nil {
				if f.Expect != "reject" || f.ExpectStage != "validate" {
					t.Fatalf("unexpected validate-stage failure: %v (want expect=%s stage=%s)", vaerr, f.Expect, f.ExpectStage)
				}
				if got := reasonFor(vaerr); got != f.ExpectReason {
					t.Fatalf("validate-stage reason mismatch: got %q, want %q (err: %v)", got, f.ExpectReason, vaerr)
				}
				return
			}

			if f.Expect != "accept" {
				t.Fatalf("expected rejection (stage=%s reason=%s) but both verify and validate succeeded", f.ExpectStage, f.ExpectReason)
			}

			sinceActivation := f.Now.Sub(lic.IssuedAt)
			inGrace := sinceActivation > maxRenewalTime && sinceActivation < lic.GracePeriod
			if inGrace != f.ExpectInGrace {
				t.Fatalf("InGracePeriod mismatch: got %v, want %v", inGrace, f.ExpectInGrace)
			}
		})
	}
}
